# docker-compose.yml
version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "3001:3001"
    depends_on:
      - mongo

  api-gateway:
    image: nginx
    container_name: api-gateway
    ports:
      - "80:80"
    volumes:
      - ./api-gateway/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - auth-service

volumes:
  mongo-data:
