version: '3.8'

services:

  ml-service:
    build: ./ml-service
    ports:
      - "8000:8000"

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "3001:3001"
    depends_on:
      - mongo

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "3002:3002"
    depends_on:
      - mongo

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "3003:3003"
    depends_on:
      - mongo
      - auth-service
      - product-service

  api-gateway:
    image: nginx
    container_name: api-gateway
    ports:
      - "80:80"
    volumes:
      - ./api-gateway/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - auth-service
      - product-service

  

volumes:
  mongo-data: