version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-net

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    networks:
      - mern-net
    volumes:
      - ./shared-utils:/app/shared-utils

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "3002:3002"
    depends_on:
      - mongo
    networks:
      - mern-net

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "3003:3003"
    depends_on:
      - mongo
      - auth-service
      - product-service
    networks:
      - mern-net
    volumes:
      - ./shared-utils:/app/shared-utils

  api-gateway:
    image: nginx
    container_name: api-gateway
    ports:
      - "80:80"
    volumes:
      - ./api-gateway/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - auth-service
      - product-service
      - order-service
    networks:
      - mern-net

  ml-service:
    build: ./ml-service
    container_name: ml-service
    ports:
      - "8000:8000"
    networks:
      - mern-net

  ml-filter-gateway:
    build: ./ml-filter-gateway
    container_name: ml-filter-gateway
    ports:
      - "3100:3100"
    depends_on:
      - ml-service
      - api-gateway
    networks:
      - mern-net

volumes:
  mongo-data:

networks:
  mern-net:
